# ============================================================================
# custom_components/kids_tasks/services.yaml
# ============================================================================

add_child:
  name: Add Child
  description: Add a new child to the kids tasks system
  fields:
    name:
      name: Child Name
      description: The name of the child
      required: true
      selector:
        text:
    avatar:
      name: Avatar
      description: Emoji or avatar URL for the child
      required: false
      selector:
        text:
    initial_points:
      name: Initial Points
      description: "Starting points for the child (default: 0)"
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          step: 1

add_task:
  name: Add Task
  description: Create a new recurring task for children
  target: {}
  fields:
    name:
      name: Task Name
      description: The name of the task
      required: true
      example: "Make bed"
      selector:
        text:
          type: text
    description:
      name: Description  
      description: Detailed description of the task
      required: false
      example: "Make the bed with clean sheets and arrange pillows"
      selector:
        text:
          type: text
          multiline: true
    category:
      name: Category
      description: Category of the task
      required: false
      default: "other"
      selector:
        select:
          options:
            - label: "Bedroom"
              value: "bedroom"
            - label: "Bathroom" 
              value: "bathroom"
            - label: "Kitchen"
              value: "kitchen"
            - label: "Homework"
              value: "homework"
            - label: "Outdoor"
              value: "outdoor"
            - label: "Pets"
              value: "pets"
            - label: "Other"
              value: "other"
          mode: dropdown
    points:
      name: Points
      description: Points awarded for completing this task
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box
    frequency:
      name: Frequency
      description: How often this task repeats
      required: false
      default: "daily"
      selector:
        select:
          options:
            - label: "Daily"
              value: "daily"
            - label: "Weekly"
              value: "weekly"
            - label: "Monthly"
              value: "monthly"
            - label: "Once"
              value: "once"
          mode: dropdown
    assigned_child_id:
      name: Assigned Child
      description: ID of the child assigned to this task (leave empty for unassigned)
      required: false
      example: "child-uuid-here"
      selector:
        text:
          type: text
    validation_required:
      name: Requires Validation
      description: Whether this task requires parental validation before awarding points
      required: false
      default: true
      selector:
        boolean:

add_reward:
  name: Add Reward
  description: Add a new reward to the rewards catalog
  fields:
    name:
      name: Reward Name
      description: The name of the reward
      required: true
      selector:
        text:
    description:
      name: Description
      description: Description of the reward
      required: false
      selector:
        text:
          multiline: true
    cost:
      name: Cost
      description: Point cost of the reward
      required: false
      default: 50
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    category:
      name: Category
      description: Category of the reward
      required: false
      default: "fun"
      selector:
        select:
          options:
            - "fun"
            - "screen_time"
            - "outing"
            - "treat"
            - "privilege"
            - "toy"
            - "other"
    limited_quantity:
      name: Limited Quantity
      description: Maximum number of times this reward can be claimed (leave empty for unlimited)
      required: false
      selector:
        number:
          min: 1
          max: 100
          step: 1

complete_task:
  name: Complete Task
  description: Mark a task as completed by a child
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to complete
      required: true
      selector:
        text:
    validation_required:
      name: Force Validation
      description: Override the task's validation setting for this completion
      required: false
      selector:
        boolean:

validate_task:
  name: Validate Task
  description: Validate a task that is pending parental approval
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to validate
      required: true
      selector:
        text:

reject_task:
  name: Reject Task
  description: Reject a task that is pending validation and reset it
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to reject
      required: true
      selector:
        text:
    reason:
      name: Reason
      description: Optional reason for rejecting the task
      required: false
      selector:
        text:

claim_reward:
  name: Claim Reward
  description: Allow a child to claim a reward using their points
  fields:
    reward_id:
      name: Reward ID
      description: Unique identifier of the reward to claim
      required: true
      selector:
        text:
    child_id:
      name: Child ID
      description: Unique identifier of the child claiming the reward
      required: true
      selector:
        text:

reset_task:
  name: Reset Task
  description: Reset a task to its initial state (to do)
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to reset
      required: true
      selector:
        text:

add_points:
  name: Add Bonus Points
  description: Add bonus points to a child (manual reward)
  fields:
    child_id:
      name: Child ID
      description: Unique identifier of the child
      required: true
      selector:
        text:
    points:
      name: Points
      description: Number of points to add
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
    reason:
      name: Reason
      description: Reason for awarding bonus points
      required: false
      selector:
        text:

remove_points:
  name: Remove Points (Penalty)
  description: Remove points from a child as a penalty
  fields:
    child_id:
      name: Child ID
      description: Unique identifier of the child
      required: true
      selector:
        text:
    points:
      name: Points
      description: Number of points to remove
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
    reason:
      name: Reason
      description: Reason for the penalty
      required: false
      selector:
        text:

update_child:
  name: Update Child
  description: Update child information
  fields:
    child_id:
      name: Child ID
      description: Unique identifier of the child to update
      required: true
      selector:
        text:
    name:
      name: New Name
      description: Updated name for the child
      required: false
      selector:
        text:
    avatar:
      name: New Avatar
      description: Updated avatar for the child
      required: false
      selector:
        text:

remove_child:
  name: Remove Child
  description: "Remove a child from the system (WARNING: This will delete all associated data)"
  fields:
    child_id:
      name: Child ID
      description: Unique identifier of the child to remove
      required: true
      selector:
        text:
    force_remove_entities:
      name: Force Remove Entities
      description: Force removal of all entities associated with this child (sensors, buttons, etc.)
      required: false
      default: false
      selector:
        boolean:

update_task:
  name: Update Task
  description: Update task properties
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to update
      required: true
      selector:
        text:
    name:
      name: New Name
      description: Updated name for the task
      required: false
      selector:
        text:
    description:
      name: New Description
      description: Updated description for the task
      required: false
      selector:
        text:
          multiline: true
    points:
      name: New Points
      description: Updated point value for the task
      required: false
      selector:
        number:
          min: 1
          max: 100
          step: 1
    category:
      name: New Category
      description: Updated category for the task
      required: false
      selector:
        select:
          options:
            - "bedroom"
            - "bathroom"
            - "kitchen"
            - "homework"
            - "outdoor"
            - "pets"
            - "other"
    active:
      name: Active Status
      description: Whether the task is active or not
      required: false
      selector:
        boolean:

remove_task:
  name: Remove Task
  description: Remove a task from the system
  fields:
    task_id:
      name: Task ID
      description: Unique identifier of the task to remove
      required: true
      selector:
        text:

update_reward:
  name: Update Reward
  description: Update reward properties
  fields:
    reward_id:
      name: Reward ID
      description: Unique identifier of the reward to update
      required: true
      selector:
        text:
    name:
      name: New Name
      description: Updated name for the reward
      required: false
      selector:
        text:
    description:
      name: New Description
      description: Updated description for the reward
      required: false
      selector:
        text:
          multiline: true
    cost:
      name: New Cost
      description: Updated point cost for the reward
      required: false
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    active:
      name: Active Status
      description: Whether the reward is active or not
      required: false
      selector:
        boolean:

remove_reward:
  name: Remove Reward
  description: Remove a reward from the catalog
  fields:
    reward_id:
      name: Reward ID
      description: Unique identifier of the reward to remove
      required: true
      selector:
        text:

reset_all_daily_tasks:
  name: Reset All Daily Tasks
  description: Reset all daily tasks to 'to do' status (typically run via automation)
  fields: {}

backup_data:
  name: Backup Data
  description: Create a backup of all kids tasks data
  fields:
    include_history:
      name: Include History
      description: Whether to include completion history in backup
      required: false
      default: true
      selector:
        boolean:

restore_data:
  name: Restore Data
  description: "Restore data from a backup (WARNING, This will overwrite current data)"
  fields:
    backup_data:
      name: Backup Data
      description: JSON backup data to restore
      required: true
      selector:
        text:
          multiline: true

clear_all_data:
  name: Clear All Data
  description: "Clear all children, tasks, and rewards (WARNING: This will delete everything)"
  fields: {}

list_tasks:
  name: List All Tasks
  description: List all tasks with their details (output will be shown in Home Assistant logs)
  fields: {}
